# Setup
title: Project or Site name
tagline: A responsive theme for your project on GitHub Pages
baseurl: "/docs"
paginate: 1
locale: "en"

# About/contact
author:
  name: 小凡
  url: http://github.com/bs3412/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
