# Setup
title: 测试
tagline: A responsive theme for your project on GitHub Pages
baseurl: "/docs"
paginate: 1
locale: "zh-cn"

# About/contact
author:
  name: 小凡
  url: http://github.com/bs3412/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
